### ISSUE TITLE
Implement PSR-1 and PSR-2

### ISSUE THREAD

**Issue by othercodes** [ingrammicro/connect-php-sdk#12]
Implement the PSR 1 and 2 to ease the implementation of future features.

- PSR-1 https://www.php-fig.org/psr/psr-1
- PSR-2 https://www.php-fig.org/psr/psr-2

Currently the repo don't follow any coding standard.

**Comment by marcserrat** [comment]
Merged pull request, starting from now PSR-1 and PSR-2 will be a must in order to accept any PR
