### ISSUE TITLE
Implement PSR-3 Logger Interface

### ISSUE THREAD

**Issue by othercodes** [ingrammicro/connect-php-sdk#7]
In order to be compliance with the PHP ecosystem it might be good to implement at least PSR-3 Logger Interface that is compliance with RFC 5424 Syslog Protocol.

PSR-3: https://www.php-fig.org/psr/psr-3/ 
RFC 5424: https://tools.ietf.org/html/rfc5424

Current Connect\Logger exposes five methods: 

- trace
- debug
- info
- error
- fatal 

The Psr\Log\LoggerInterface exposes eight methods:

- emergency
- alert
- critical
- error
- warning
- notice
- info
- debug

**Comment by marcserrat** [comment]
Dear Unay,
thanks for this. Logger will be improved as part of improvements relative to operations that will come in upcomming versions of SDK

**Comment by marcserrat** [comment]
merged on autotesting branch. to be released as 1.1
