### ISSUE TITLE
var keyword generate an E_STRICT warning in PHP 5 (before 5.1.3)

### ISSUE THREAD

**Issue by othercodes** [ingrammicro/connect-php-sdk#9]
The usage of `var` keyword is not recommended, use `public` instead in all classes of sdk.php file

http://php.net/manual/en/language.oop5.visibility.php

> Note: The PHP 4 method of declaring a variable with the var keyword is still supported for compatibility reasons (as a synonym for the public keyword). In PHP 5 before 5.1.3, its usage would generate an E_STRICT warning.

**Comment by marcserrat** [comment]
Fixed and released on version 1.0.4
